import type { Metadata } from "next";
import vazirmatnLocal from "next/font/local";
import "./css/globals.css";
import AdminLayout from "../modules/layout/AdminLayout";
import IconDoctor from "@/src/assest/IconTab/Background decoration.png"

const vazirmatn = vazirmatnLocal({
  src: "../assest/font/Vazirmatn-Medium.ttf",
});
const IranYekan = vazirmatnLocal({
  src: "../assest/font/IRANYekanXFaNum-Medium.ttf",
});
 
export const metadata: Metadata = {
  title: "Doctor",
  description: "Generated by create next app",
  icons: IconDoctor.src,
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="fa" dir='rtl' className="h-full antialiased">
      <body className={`${vazirmatn.className} ${vazirmatn.style} ${IranYekan.className} ${IranYekan.style}  antialiased min-h-full w-full  flex flex-col`}  >
        <div className=" flex w-full ">
          <AdminLayout />
        </div>
        <div className="flex w-full  flex-1 min-h-0">{children}</div>
      </body>
    </html>
  );
}
