import type { Metadata } from "next";
import vazirmatnLocal from "next/font/local";
import "./css/globals.css";
import AdminLayout from "../modules/layout/AdminLayout";

const vazirmatn = vazirmatnLocal({
  src: "../assest/font/Vazirmatn-Medium.ttf",
});

export const metadata: Metadata = {
  title: "Doctor",
  description: "Generated by create next app",
  icons: {
    shortcut: "data:image/",
  },
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="fa" className="h-full antialiased">
      <body className={`${vazirmatn.className} ${vazirmatn.style}  antialiased min-h-full w-full  flex flex-col`}  >
        <div className=" flex w-full ">
          <AdminLayout />
        </div>
        <div className="flex w-full  flex-1 min-h-0">{children}</div>
      </body>
    </html>
  );
}
