import type { Metadata } from "next";
import vazirmatnLocal from "next/font/local";

import "./css/globals.css";

import IconDoctor from "@/src/assest/IconTab/Background decoration.png";
import { AuthProvider } from "@/src/shared/auth/AuthProvider";

const vazirmatn = vazirmatnLocal({
  src: "../assest/font/Vazirmatn-Medium.ttf",
});

const IranYekan = vazirmatnLocal({
  src: "../assest/font/IRANYekanXFaNum-Medium.ttf",
});

export const metadata: Metadata = {
  title: "Doctor",
  description: "Generated by create next app",
  icons: IconDoctor.src,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa"
      dir="rtl"
      className="h-full antialiased"
    >
      <body
        className={`
          ${vazirmatn.className}
          ${IranYekan.className}
          antialiased
          min-h-full
          w-full
        `}
      >
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}